language: node_js
os: linux
cache: yarn
node_js:
  - 6
  - stable
after_success:
  - yarn add codecov
  - "./node_modules/.bin/iamtest -c lcovonly && ./node_modules/.bin/codecov"
env:
  global:
  - secure: Zdkp6WqoUzfjPKIX/voWK1uRY/d7GML9t8RSS1ACI6kbgnO2oSaLQVgsn0DmCRfaTJoMLbyhytj7luLVxBaB99YCbs7567Fizq6gRAoqiUs4320P05++bO/oSP8PENB4sjQqC4N7+aq49sc15Hu40GTORJl4EvlzQoVd6Oc53B6ZYNGVnoNllKhSecTTVwQPR1E57RNmuMUhJNQkpGb9QFLtqdZNXhXiLhjbtynf/7whecKwOMgOFDEtV5+MU4s/x/7x10rm5e8BEl3fKuCG87/7X6fxICBO5Edsfm4HJlWlG7NXXolYuN0LYhLCu8f8OqnWpkdUyxCAU/1xucvfTtsPMLO6dQ/yHQt1H+WzW5L5zukQ/96g5W9sxZqCHD6E/cy+IhYIiAUm6UJprr5zp6OxgYV8IOmr4RpGYLN7KT4aYlfFEkdU26UQzEf9T7mNwZufoGNgE6PXzUwMpZ8Y9jK/BNEYyMtAgrAGij6m6H4R74DyLF1yYkRzGEeObh2EonepS9UDtmlnF+XHQUGSrfy0cFTeDdQ+RCn6OyMtzkanJI5vyWlRFZKmcuCxiUZZxmQhnf7awgHX3bjGcER1oo54bP+BHZ9A/Ir2ncTLV7lNB40kG5icudhjBRB94yRV5Svf+B8vcwr/Twz8gKueeX7YxA09vPK/wquxpqyOB6E=
  - secure: fjhke+3oGyTeb4O7Pn9yUud0jOhnDbqgbD9haCyvpbZfIOSraHJ7QEp7TYrpa6HiGpwscwrKYrjUq4ob3HTBX/8KIpjLch+xg1Z/wJ4w3dkqjk1xq+dH6sGyflP6+ZJVoEcD6PaoYPReNEeFY1esb6GkvxAY6Y+6VEZYopL6yZEapwaS04lajurazkGLFP9uswCf4xr59g5zuO6JinY5qKe0B18IL2w12znCQK1MP0cOaL3JjjB+BzVB8D6IbPJIwikrH02hPYHe76cdLoj3QRbJemPxWsI5XAqSTZxQ+efrDKCulE5CyA08SwbvX7WTN042wFDZsrRbG1In6fjpvpytGusXoAShTz5I39ox2b5BeXlSbfgBzJYVYtEU23Uwljs4WYHUuDyzcn97DfoXz7nLCoioxouD/0QFd+uXQNw3LS0RKMw+j/xLPhVV7ViWA43uK0xNfnpzzj0Sek3KzmrWCx9vWS0h+/N8G5O4RToibRWKli3RIVSrQdSFI27XHBB4chxQQHYLL2Qw5VygYwpl+GyTMx0WTkHnwjAhy8mr6DG8dVFUBxCQiV1ss+qeyNMCjkFLVoUtWbED37+m40HLw+QoQcT55CpN1LZKCkJaJ/uuBgwBJuifYaYG6XY/th3boCa6t6KeReb4PXmN6ttU1EYj43PvX1WdFHeeUY8=
deploy:
  provider: npm
  email: anton@mokr.org
  api_key:
    secure: O/+2SGpNXb9pwhLepPS3ZcvLq57aD3aovWZztZmML3QAWQzHSSj29+AYa77v9QuwG8TqUmdzSm7pZGUuhom8bj6jsgoOFYDeirTuhw97MTDY2eNKML2Z7UHmhdMuLx9m0rwafKuEONFnm05r674W5KHOszSAdXpCPymX3X9qymzsFM/ddQP+MrxIHeX3TZP9Up07yXhAn+dFuiWlHVKKfsY0FaegdMAiaxrmFDj3/n67G+SadAxKc1WIKKeUcnDWrkRxZVEd2zqXqwPE7hz/cyLY9iPQdb/d9WffPXTw+8PnCxdyXYMW0gGOZaiOJ4dHfxUZFo6RThEsyrUI1m5xZTXGUAxc1tuIs7SSSGwaNkwkuEESBNt3kR5tizeZ9tKLfKwVj8Nk70a4ZBKp3hfSXeD/cqugG9dLxcR/tzKod1tzAHtpszAY9Y7xWH3A2TkE+do/Xg2FlHe0jruYhRH+xmG7cjIu27vFLNBgFnTz02jdtn5cmROUs9ETKU9krqkFJh326G9HyLZk+lH31PtDbEN3UR720D7O8ERm+Xsb2FEvH37kVnpm0l+moRovJhAy0h08RM+0wbMTrSz2jM0OeWGDVSsi+XbnweFDwGgaaFkWk0BlVK1iDKnvwayDtTd9mcI1NJWPtGblk9AQQUIz4GtDxL8O/z0Ff2SZ16zW2aE=
  on:
    tags: true
    repo: amokrushin/stream-multipart-upload
    branch: master
